import 'package:splitbliss/models/notify.dart';

import 'package:splitbliss/enums.dart';

final List<Notify> notify = [
  Notify(
    'You are added to a new room',
    'Gear 5 Nika man',
    'ramvinay609',
    Type.Added_To_Group,
    DateTime(2023, 9, 24),
  ),
  Notify(
    'Please add the money in the Room',
    'Jagwar Gang',
    'ramvinay609',
    Type.Add_Money_To_Group,
    DateTime(2023, 9, 24),
  ),
  Notify(
    'Ram is requesting you the money',
    'Romane Trip',
    'ramvinay609',
    Type.Requesting_Money,
    DateTime(2023, 8, 23),
  ),
  Notify(
    'samuel sent money.Confirm it',
    'Jagwar Gang',
    'ramvinay609',
    Type.Added_To_Group,
    DateTime(2023, 8, 23),
  ),
  Notify(
    'You are added to a new room',
    'Gear 5 Nika man',
    'ramvinay609',
    Type.Added_To_Group,
    DateTime(2023, 8, 8),
  ),
  Notify(
    'You are added to a new room',
    'Gear 5 Nika man',
    'ramvinay609',
    Type.Added_To_Group,
    DateTime(2023, 7, 23),
  ),
  Notify(
    'You are added to a new room',
    'Gear 5 Nika man',
    'ramvinay609',
    Type.Added_To_Group,
    DateTime(2023, 3, 23),
  ),
  Notify(
    'You are added to a new room',
    'Gear 5 Nika man',
    'ramvinay609',
    Type.Added_To_Group,
    DateTime(2023, 9, 24),
  ),
  Notify(
    'Please add the money in the Room',
    'Jagwar Gang',
    'ramvinay609',
    Type.Add_Money_To_Group,
    DateTime(2023, 9, 24),
  ),
  Notify(
    'Ram is requesting you the money',
    'Romane Trip',
    'ramvinay609',
    Type.Requesting_Money,
    DateTime(2023, 8, 23),
  ),
  Notify(
    'samuel sent money.Confirm it',
    'Jagwar Gang',
    'ramvinay609',
    Type.Added_To_Group,
    DateTime(2023, 8, 23),
  ),
  Notify(
    'You are added to a new room',
    'Gear 5 Nika man',
    'ramvinay609',
    Type.Added_To_Group,
    DateTime(2023, 8, 8),
  ),
  Notify(
    'You are added to a new room',
    'Gear 5 Nika man',
    'ramvinay609',
    Type.Added_To_Group,
    DateTime(2023, 7, 23),
  ),
  Notify(
    'You are added to a new room',
    'Gear 5 Nika man',
    'ramvinay609',
    Type.Added_To_Group,
    DateTime(2023, 3, 23),
  ),
  Notify(
    'You are added to a new room',
    'Gear 5 Nika man',
    'ramvinay609',
    Type.Added_To_Group,
    DateTime(2023, 9, 24),
  ),
  Notify(
    'Please add the money in the Room',
    'Jagwar Gang',
    'ramvinay609',
    Type.Add_Money_To_Group,
    DateTime(2023, 9, 24),
  ),
  Notify(
    'Ram is requesting you the money',
    'Romane Trip',
    'ramvinay609',
    Type.Requesting_Money,
    DateTime(2023, 8, 23),
  ),
  Notify(
    'samuel sent money.Confirm it',
    'Jagwar Gang',
    'ramvinay609',
    Type.Added_To_Group,
    DateTime(2023, 8, 23),
  ),
  Notify(
    'You are added to a new room',
    'Gear 5 Nika man',
    'ramvinay609',
    Type.Added_To_Group,
    DateTime(2023, 8, 8),
  ),
  Notify(
    'You are added to a new room',
    'Gear 5 Nika man',
    'ramvinay609',
    Type.Added_To_Group,
    DateTime(2023, 7, 23),
  ),
  Notify(
    'You are added to a new room',
    'Gear 5 Nika man',
    'ramvinay609',
    Type.Added_To_Group,
    DateTime(2023, 3, 23),
  ),
  Notify(
    'You are added to a new room',
    'Gear 5 Nika man',
    'ramvinay609',
    Type.Added_To_Group,
    DateTime(2023, 9, 24),
  ),
  Notify(
    'Please add the money in the Room',
    'Jagwar Gang',
    'ramvinay609',
    Type.Add_Money_To_Group,
    DateTime(2023, 9, 24),
  ),
  Notify(
    'Ram is requesting you the money',
    'Romane Trip',
    'ramvinay609',
    Type.Requesting_Money,
    DateTime(2023, 8, 23),
  ),
  Notify(
    'samuel sent money.Confirm it',
    'Jagwar Gang',
    'ramvinay609',
    Type.Added_To_Group,
    DateTime(2023, 8, 23),
  ),
  Notify(
    'You are added to a new room',
    'Gear 5 Nika man',
    'ramvinay609',
    Type.Added_To_Group,
    DateTime(2023, 8, 8),
  ),
  Notify(
    'You are added to a new room',
    'Gear 5 Nika man',
    'ramvinay609',
    Type.Added_To_Group,
    DateTime(2023, 7, 23),
  ),
  Notify(
    'You are added to a new room',
    'Gear 5 Nika man',
    'ramvinay609',
    Type.Added_To_Group,
    DateTime(2023, 3, 23),
  ),
  Notify(
    'You are added to a new room',
    'Gear 5 Nika man',
    'ramvinay609',
    Type.Added_To_Group,
    DateTime(2023, 9, 24),
  ),
  Notify(
    'Please add the money in the Room',
    'Jagwar Gang',
    'ramvinay609',
    Type.Add_Money_To_Group,
    DateTime(2023, 9, 24),
  ),
  Notify(
    'Ram is requesting you the money',
    'Romane Trip',
    'ramvinay609',
    Type.Requesting_Money,
    DateTime(2023, 8, 23),
  ),
  Notify(
    'samuel sent money.Confirm it',
    'Jagwar Gang',
    'ramvinay609',
    Type.Added_To_Group,
    DateTime(2023, 8, 23),
  ),
  Notify(
    'You are added to a new room',
    'Gear 5 Nika man',
    'ramvinay609',
    Type.Added_To_Group,
    DateTime(2023, 8, 8),
  ),
  Notify(
    'You are added to a new room',
    'Gear 5 Nika man',
    'ramvinay609',
    Type.Added_To_Group,
    DateTime(2023, 7, 23),
  ),
  Notify(
    'You are added to a new room',
    'Gear 5 Nika man',
    'ramvinay609',
    Type.Added_To_Group,
    DateTime(2023, 3, 23),
  ),
];
